root: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
parserOptions:
    project: './tsconfig.json'
    sourceType: 'module'
ignorePatterns:
    - 'scripts/*'
    - '*.config.js'
    - 'lib/*'
    - 'examples/*'
    - 'coverage/*'
    - 'node_modules/*'
    - '.yarn/*'
    - '.nyc_output/*'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
